plugins {
    id 'com.github.burrunan.s3-build-cache' version '1.9.5'
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

ext.isCi = System.getenv('CI') != null

buildCache {
    local { enabled = !isCi }
    remote(com.github.burrunan.s3cache.AwsS3BuildCache) {
        region = 'us-east-1'
        bucket = 'my-ci-cache'
        prefix = 'gradle-build-cache/'
        endpoint = System.getenv('S3_ENDPOINT') ?: ''
        push = isCi
    }
}

rootProject.name = 'msa-shop'

include 'service:common'
include 'service:user'
include 'service:order'
